# Copyright © 2019 State Street Bank and Trust Company.  All rights reserved
#
# SPDX-License-Identifier: Apache-2.0

version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/lib
    docker:
      - image: openjdk:14-alpine3.10
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          shell: /bin/sh
          command: |
            apk add --no-progress --no-cache \
               make \
               bash \
               nss
            ./lein deps
      - run: make all
      - run: |
          mkdir tmp
          mv target/protojure-* tmp
      - store_artifacts:
          path: tmp/
          destination: jar
